services:
  react:
    build: .
    container_name: react-vite
    ports:
      - "5173:5173"
    volumes:
      - ./app-react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: >
      sh -c "
      npm run dev -- --host
      "
