services:
  react:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./app-react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: >
      sh -c "
      npm install && npm run dev -- --host
      "
  bd:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./db:/app
    command: >
      sh -c "
      npm install && npx json-server --port 3001 --watch db.json
      "